-- TABLE FIDÈLES
CREATE TABLE IF NOT EXISTS fideles (
  id              BIGSERIAL PRIMARY KEY,
  nom             TEXT NOT NULL,
  prenom          TEXT,
  tel             TEXT,
  quartier        TEXT,
  profession      TEXT,
  categorie       TEXT NOT NULL DEFAULT 'Adulte' CHECK (categorie IN ('Adulte','Enfant')),
  engagement      NUMERIC(12,2) DEFAULT 0,
  engagement_fige NUMERIC(12,2) DEFAULT 0,
  vers_init       NUMERIC(12,2) DEFAULT 0,
  is_new          BOOLEAN DEFAULT FALSE,
  created_at      TIMESTAMPTZ DEFAULT NOW(),
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

-- TABLE VERSEMENTS
CREATE TABLE IF NOT EXISTS versements (
  id             BIGSERIAL PRIMARY KEY,
  fidele_id      BIGINT NOT NULL REFERENCES fideles(id) ON DELETE CASCADE,
  mois_index     INTEGER NOT NULL CHECK (mois_index BETWEEN 0 AND 10),
  montant        NUMERIC(12,2) DEFAULT 0,
  date_versement DATE,
  created_at     TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(fidele_id, mois_index)
);

-- TRIGGER updated_at
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN 
  NEW.updated_at = NOW(); 
  RETURN NEW; 
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at ON fideles;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON fideles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- INDEX
CREATE INDEX IF NOT EXISTS idx_fideles_categorie ON fideles(categorie);
CREATE INDEX IF NOT EXISTS idx_fideles_nom ON fideles(nom);
CREATE INDEX IF NOT EXISTS idx_versements_fidele ON versements(fidele_id);

-- RLS
ALTER TABLE fideles   ENABLE ROW LEVEL SECURITY;
ALTER TABLE versements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "lecture publique fideles"    ON fideles;
DROP POLICY IF EXISTS "ecriture auth fideles"       ON fideles;
DROP POLICY IF EXISTS "lecture publique versements" ON versements;
DROP POLICY IF EXISTS "ecriture auth versements"    ON versements;

CREATE POLICY "lecture publique fideles"    ON fideles   FOR SELECT USING (true);
CREATE POLICY "ecriture auth fideles"       ON fideles   FOR ALL    USING (auth.role() = 'authenticated');
CREATE POLICY "lecture publique versements" ON versements FOR SELECT USING (true);
CREATE POLICY "ecriture auth versements"    ON versements FOR ALL    USING (auth.role() = 'authenticated');

-- REALTIME (version qui fonctionne)
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
        AND tablename = 'fideles'
        AND schemaname = 'public'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE fideles;
    END IF;
    
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
        AND tablename = 'versements'
        AND schemaname = 'public'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE versements;
    END IF;
END $$;

-- INSERT
INSERT INTO fideles (nom, prenom, tel, quartier, profession, categorie, engagement, engagement_fige, vers_init, is_new, created_at, updated_at) VALUES
('ABADJENE', 'Etsè', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('ABAFOUM', 'Alimatou', '92 07 87 31', '', 'Etudiante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ABALO', 'Kodzo Cyril', '99 65 83 76', '', 'Coordinateur d''ONG', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ABALO', 'Komlavi Edem', '90 17 78 75', '', 'Commerçant', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ABELE', '', '', '', '', 'Adulte', 30000, 0, 0, false, NOW(), NOW()),
('ABELE', 'Essowaba Victoire', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('ABEOU', 'Brigitte', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('ABODA', 'Augustin', '', '', '', 'Adulte', 100000, 0, 10000, false, NOW(), NOW()),
('ABODA', 'Koomlavi Remi', '90 12 18 34', 'Totsi', 'Gérant de boutique', 'Adulte', 30000, 0, 0, false, NOW(), NOW()),
('ABOFLAN', 'Amivi Eménéfa Essé', '79 92 21 05', 'Agbalepedo', 'Tisserante', 'Adulte', 5000, 0, 0, false, NOW(), NOW()),
('ABOLO', 'Kodzo', '', '', '', 'Adulte', 250000, 0, 0, false, NOW(), NOW()),
('ABOUGA', 'Afi', '98 63 36 00', 'Totsi', 'Revendeuse', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('ADABRASSATSE', 'Koffi', '98 92 81 37', 'Djidjolé', 'Menuisier', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ADADE', 'Kayi', '97 62 16 46', '', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ADAMAH', 'Ranle Delali Dionel', '92 13 33 35', 'Djidjolé', 'Revendeuse', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('ADAMENOU', 'Massan', '90 56 52 29', 'Gblékome', 'Ménagère', 'Adulte', 100000, 0, 10000, false, NOW(), NOW()),
('ADIKATCHO', 'Afi Philomène', '91 42 72 73', 'Djidjolé', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ADIKATCHO', 'Afi', '91 42 72 73', '', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ADJA', 'Emmanuel', '92 33 76 52', '', 'Revendeur', 'Adulte', 100000, 0, 100000, false, NOW(), NOW()),
('ADJESSON', 'Afi Dado', '92 48 10 29', '', 'Commerçante', 'Adulte', 50000, 0, 10000, false, NOW(), NOW()),
('ADOM', 'Chimène', '90 29 39 94', 'Totsi', 'Secrétaire', 'Adulte', 12000, 0, 0, false, NOW(), NOW()),
('ADOMEVO', 'Afi Manda', '97 97 97 38', 'Djidjolé', '', 'Adulte', 30000, 0, 5000, false, NOW(), NOW()),
('ADONSI', 'Bruno', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('ADONSI', 'Adjo Antoinette', '96 32 72 02', 'Adidogomé', 'Entrepreneur', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ADONVI', 'A. Victor', '93 38 76 30', 'Legbassito', 'Enseignant', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('ADZAKLO', 'Adzo Olivia', '97 83 67 89', 'Batomé', 'Infirmière', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('AFAGNON', 'Amélie', '90 63 87 91', 'Djidjolé', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AFANDE', 'Assoupi', '', '', '', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('AFANGBEGNON', 'Adjo Enyonam Orlane', '97 33 97 17', 'Agbalepedo', 'Etudiante', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('AFIDEWOU', 'Abina Sylvia', '', 'Totsi', 'Elève', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AFOKPA', 'Delali Flora', '91 42 42 19', 'Totsi', 'Secrétaire', 'Adulte', 150000, 0, 0, false, NOW(), NOW()),
('AFOTOR', 'Akoua', '91 67 95 70', '', 'Couturière', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('AGAYI', 'Ana', '91 77 25 05', 'Soviépé', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AGBAGO', 'Akouvi Marie', '90 45 89 51', 'Totsi', 'Sage femme', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AGBAGO', 'Komlan Désiré', '98 15 07 21', 'Totsi', 'Gestionnaire', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AGBANA', 'Komi Edoh', '96 07 85 77', '', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AGBASSE', 'Fifi denise', '', '', '', 'Adulte', 30000, 0, 0, false, NOW(), NOW()),
('AGBASSOU', 'Adjo Annick', '93 63 28 89', '', 'Comptable', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AGBEGNIDO (Anc)', 'Magloire', '', '', '', 'Adulte', 1000000, 0, 0, false, NOW(), NOW()),
('AGBEKO', 'Espéré', '93 50 76 79', 'Djidjolé', 'Agent commercial', 'Adulte', 15000, 0, 2000, false, NOW(), NOW()),
('AGBEKO', 'Kossiwa Bénedicte', '91 62 13 13', 'Totsi', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AGBEKO', 'Yawa Edi Love', '98 15 00 41', 'Fransiscain', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AGBESSI', 'A. Kossi', '', '', '', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('AGBLOYOE', 'Komi Mawulé', '99 32 67 27', 'Djidjolé', 'Etudiant', 'Adulte', 100000, 0, 0, false, NOW(), NOW()),
('AGBLOYOE', 'Akouavi', '79 78 05 17', 'Djidjolé', 'Etudiante', 'Adulte', 25000, 0, 0, false, NOW(), NOW()),
('AGBOKANZO', 'A. Béatrice', '93 01 34 28', '', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AGBOKOU', 'Amélie', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('AGBOKOU', 'Yao Mokpokpo', '92 26 85 94', 'Djidjolé', 'Enseignant', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('AGBOLESSOU', 'Julienne', '', '', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AGBOLESSOU', 'Akouvi', '91 56 22 30', 'Totsi', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AGBOLESSOU', 'Anicette', '91 38 28 05', 'Totsi', 'Apprentis couturière', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AGBONE', 'Akouvi Fidel', '91 57 28 31', '', 'Ménagère', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AGLI', 'Amivi Déborah', '90 70 20 89', 'Avenou', 'Elève', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('AGNAN', 'Linda', '91 59 04 84', 'Batomé', 'Serveuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AGNIGNI', 'Kodjo Michel', '98 56 93 13', 'Totsi', 'Mécanique-Auto', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('AGNINDE', 'Rodiatou', '99 59 76 56', 'Gblékome', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('AGNINI', 'Essi Déborah', '93 33 57 27', 'Totsi', 'Etudiante', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('AGNINI (Diac)', 'Abla', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('AGOE', 'Aiméé Essi', '98 90 14 64', 'Avedji', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AGOSSOU', 'Gaston', '90 98 28 72', '', 'Maçon', 'Adulte', 25000, 0, 0, false, NOW(), NOW()),
('AHADJI', 'Afi', '92 25 01 89', '', 'Commesçante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AHIAGBA', 'REGINE', '', '', '', 'Adulte', 20000, 0, 10000, false, NOW(), NOW()),
('AHIAGBA', 'Kossivi Seth', '91 58 46 15', 'Djidjolé', 'Enseignant', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AHIAGBA', 'Béni K.', '91 95 59 62', 'Totsi', '', 'Adulte', 250000, 0, 0, false, NOW(), NOW()),
('AHLANKO', 'Ayélévi Yvette', '92 28 91 73', '', 'Caissière', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AHOULOUMA', 'Ednam', '90 03 57 90', 'Avedji', 'Assistante sociale', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AJANKONOU', 'Maman', '', '', '', 'Adulte', 2500, 0, 0, false, NOW(), NOW()),
('AKAKPO', 'Kossiwavi', '91 92 16 70', 'Gblékome', 'Etudiante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AKAKPO', 'Adjovi Essé Martine', '90 94 19 24', 'Batomé', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AKANA', 'David', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('AKANA', 'Emile', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('AKOEGNEKOU', 'Dédé', '', '', 'Commerçante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AKOTEM', 'Abla Justine', '91 11 96 41', 'Totsi', 'Tresseuse', 'Adulte', 5000, 0, 0, false, NOW(), NOW()),
('AKOTO', 'M. Victoire Mélanie', '98 48 03 42', '', 'Couturière', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AKOULA', 'Komi Samuel', '90 54 46 60', '', 'Revendeur', 'Adulte', 30000, 0, 2000, false, NOW(), NOW()),
('AKOUTA', 'Ayomo David', '93 08 51 66', '', 'Etudiant', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ALASSANI', 'Méminatou', '91 40 08 03', '', 'Commerçante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ALATABOU', 'Asmanou', '71 17 36 44', 'Agbalepedo', 'Electricien-Auto', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ALAZA', 'Mubutu Moîse', '92 45 91 02', 'Agbalepedo', 'Electricien-Auto', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ALENOUDEWOKO', 'Yawa Jeannette', '71 83 65 41', '', 'Etudiante', 'Adulte', 5000, 0, 0, false, NOW(), NOW()),
('ALLOH', 'Houmaizou Maina', '96 32 81 15', 'Tokoin séminaire', 'Medecin', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AMAGNO', 'Abashe', '', '', '', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('AMANYO', 'Agath', '98 86 19 70', '', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AMEDEGNATO', 'Jeanine', '', '', '', 'Adulte', 500000, 0, 0, false, NOW(), NOW()),
('AMEDENDI', 'Djodjina', '91 38 02 43', '', 'Etudiante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AMEGAN', 'Akouvi Adèle', '98 07 35 33', 'Agbalepedo', 'Cuisinière', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('AMELONKOU', 'Agossou Aimé', '90 98 65 44', '', 'Masseur', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AMEMALIGBE', 'Afi', '97 55 09 53', '', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AMENYOWU', '', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('AMENYOWU', 'Yaovi Albert', '98 38 31 43', 'Amadahomé', 'Peintre bâtiment', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('AMENYOWU', 'Hélène', '98 19 62 01', 'Vakpossito', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AMETI', 'Viviane', '93 33 22 11', '', 'Revendeuse', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('AMETONAGNO', 'Koudjo', '98 03 90 59', 'Totsi', 'Gestionnaire d''immeuble', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('AMEZADO', 'Messan Jean', '90 83 15 99', 'Legbassito', 'Gestionnaire comptable', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AMOENI', 'Akossiwa', '70 15 53 65', 'Gblékome', '', 'Adulte', 10000, 0, 5000, false, NOW(), NOW()),
('AMOENI', 'Abram Samuel', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('AMOENY', 'Reine Ama', '93 94 58 46', 'Totsi', 'Juriste privatiste', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AMOENY', 'Néhémie Komlan', '93 94 58 45', 'Totsi', 'Etudiant', 'Adulte', 60000, 0, 10000, false, NOW(), NOW()),
('AMOENY', 'Yosua Romuald', '98 46 13 26', 'Tokoin Protestant', 'Revendeur', 'Adulte', 250000, 0, 5000, false, NOW(), NOW()),
('AMOENY', 'Elom Cécile', '', '', '', 'Adulte', 100000, 0, 0, false, NOW(), NOW()),
('AMOENY (Apôtre)', 'Ayao Grégoire', '90 28 11 91', 'Gblékome', 'Apôtre', 'Adulte', 1000000, 0, 50000, false, NOW(), NOW()),
('AMOENY (Diac)', 'Amélé Christine', '70 78 51 39', 'Totsi', 'Commerçante', 'Adulte', 50000, 0, 10000, false, NOW(), NOW()),
('AMOENY(Mme Apôtre)', 'Nayi Emma', '90 65 91 16', 'Gblékome', 'Ménagère', 'Adulte', 50000, 0, 10000, false, NOW(), NOW()),
('AMOSSOU', 'Afi Olive', '93 59 65 82', 'Agoe Anomè', 'Agronome', 'Adulte', 50000, 0, 10000, false, NOW(), NOW()),
('AMOSSOU', 'Edoh Théophile', '92 60 07 76', 'Totsi', 'Etudiant', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AMOU', 'Etonam Gillence', '91 73 68 35', 'Totsi', 'Etudiante', 'Adulte', 25000, 0, 0, false, NOW(), NOW()),
('AMOU', 'Eyrame', '70 12 36 93', '', 'Apprentis', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('AMOU', 'Marie', '72 40 94 50', '', 'Revendeuse', 'Adulte', 20000, 0, 2000, false, NOW(), NOW()),
('AMOU', 'Florence Jolie', '92 24 96 26', '', 'Revendeuse', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('AMOUZOU', 'Antoine', '91 49 83 66', 'Avedji', 'Chômage', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('AMOUZOU', 'Christine', '92 95 16 70', 'Lomégan', 'Etudiante', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('AMOUZOUVI', 'Adjoa', '', '', 'Revendeuse', 'Adulte', 250000, 0, 50000, false, NOW(), NOW()),
('ANOELE', 'Innocent', '93 89 72 32', 'Totsi', 'Ingenieur en geni civil', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ANOUDJA', 'Benjamin', '79 43 06 87', '', 'Carroleur', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('APEGNEKOU', 'Akpedjé Rose', '', '', '', 'Adulte', 15000, 0, 0, false, NOW(), NOW()),
('ASSIAGBO', 'Komi Dovenè', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('ASSIDENOU', 'Prudence', '93 13 14 95', 'Cacaveli', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ASSOGBA', 'Apollinaire Beauga', '91 50 03 53', 'Agbalepedo', 'Technicien en plomberie forage', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ASSOGBA', 'Brigitte', '70 02 61 10', '', 'Etudiant', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('ASSOU', 'Kossiwa', '93 86 43 42', '', 'Styliste', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ATAGLO', 'Kodjo', '99 47 48 47', 'Gblékome', 'Chauffeur', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('ATAKOUI (Anc)', 'Massamesso David', '90 29 16 14', 'Lomégan', 'Enseignant', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('ATAKOUYI', 'Gédéon', '71 76 61 89', '', 'Etudiant', 'Adulte', 5000, 0, 0, false, NOW(), NOW()),
('ATCHERE', 'Nandjetemba', '92 54 50 95', 'Totsi', 'Cordonnier', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ATCHERE', 'Ami Pelagie', '91 73 51 66', 'Totsi', 'Coiffeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ATCHOU', 'Kokou Rodrigue', '92 19 02 70', 'Tokoin', 'Magasinier', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ATCHOU-GATO', 'N''Diga Edmond', '98 16 39 04', '', 'Coiffeur', 'Adulte', 5000, 0, 0, false, NOW(), NOW()),
('ATTAH', 'Kokou Salomon', '96 58 15 80', '', 'Etudiant', 'Adulte', 5000, 0, 0, false, NOW(), NOW()),
('AUANI', 'Kossi Elom', '92 12 62 82', 'Cacaveli', 'Délégué médical', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AVETOR', 'Kossiwa Brigitte', '92 25 10 03', '', 'Revendeuse', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('AVOGAH', 'Margueritte', '', '', '', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('AVOUDJIGBE', 'Koami', '99 27 35 44', 'Totsi', 'Agent immobilier', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AWATSOU', 'Samuel', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('AWESSO', 'Prénam Sarah', '91 86 03 84', 'Totsi', 'Commerçante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AWESSO', 'Prénam', '', '', '', 'Adulte', 30000, 0, 0, false, NOW(), NOW()),
('AYANOU', 'Kossi Amen', '79 62 41 43', '', 'Tapissier', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AYEKPO', 'Komi Claude', '92 47 95 79', 'Totsi', 'Juriste', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('AYEKPO', 'Kafui Reine', '91 47 47 79', 'Gblékome', 'Etudiante', 'Adulte', 100000, 0, 0, false, NOW(), NOW()),
('AYEKPO (Diac)', 'Kossiba', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('AYETCHE', 'Assogba Pacôme', '99 71 56 71', 'Djidjolé', 'Etudiante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('AYIFODOU', 'Sandrine', '', '', '', 'Adulte', 100000, 0, 0, false, NOW(), NOW()),
('AYOR', 'E. Samuel', '97 10 14 93', 'Adidogomé', 'Gestionnaire', 'Adulte', 100000, 0, 0, false, NOW(), NOW()),
('AZANKPO', 'Kodjovi A. John', '92 10 04 19', 'Agoe téléssou', 'Enseignant', 'Adulte', 30000, 0, 5000, false, NOW(), NOW()),
('AZIADOGBE', 'Komla Emile', '96 01 71 85', '', 'Etudiant', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('AZIAGBEGNON', 'Akou', '', '', '', 'Adulte', 10000, 0, 2000, false, NOW(), NOW()),
('BADJALE', 'Ayigré Barth', '91 38 96 30', 'Vakpossito', 'Moniteur Auto-école', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('BADJILIMA', 'Komana', '90 08 81 97', 'Djidjolé', 'Couturière', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('BADJILIMA', 'Ahefa', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('BAGNALBASSIMA', 'Akoua', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('BALAKIM', 'Ahléno Paulin', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('BALAKIM', 'Justin', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('BAMOI', 'Komlavi', '91 77 05 98', '', 'Etuduant', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('BARNABO (Servte)', 'Yendoutié', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('BATISSI', 'Essognim', '97 70 81 39', 'Totsi', 'Etudiant', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('BELLO', 'Amina', '92 44 39 47', 'Djidjolé', 'Revendeuse', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('BOLTAME', 'Yendouboan Gérard', '90 91 58 63', 'Batomé', 'Infirmier d''Etat', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('BOMADI', 'Hervé', '92 06 23 53', 'Totsi', 'Elève', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('BOMADI', 'Ervé', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('BOURAIMA', 'Koudiratou', '91 20 58 70', 'Totsi', 'Commerçante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('DAGBA', 'Amen', '98 75 70 97', 'Totsi', 'Etudiant', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('DAGBA', 'Kokou Edem', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('DAGBA', 'Essé', '72 40 01 53', '', 'Etudiant', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('DAGBA', 'Mawugnon', '72 40 01 54', '', 'Etudiante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('DAMOIN', 'Akouvi Appoline', '70 65 04 58', 'Totsi', 'Tresseuse', 'Adulte', 5000, 0, 0, false, NOW(), NOW()),
('DANSOU', 'Agayi Kodjo Elagnon', '92 17 18 54', 'Agbalepedo', '', 'Adulte', 15000, 0, 10000, false, NOW(), NOW()),
('DANSOU', 'Ami', '92 73 31 49', 'Glekome', 'Volontaire CDE', 'Adulte', 5000, 0, 0, false, NOW(), NOW()),
('DANSOU-PEDANOU', 'Kodjovi Mawulom', '90 10 70 04', 'Agoe téléssou', 'Electricien bâtiment', 'Adulte', 25000, 0, 0, false, NOW(), NOW()),
('DAOU (Anc)', 'Justin', '', '', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('DEGBE', 'Kossi Frédéric', '90 71 11 94', 'Totsi', 'Comptable', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('DEGBE', 'Makafui Dado', '99 88 76 89', 'Totsi', 'Commerçante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('DEGUENON', 'Rosa', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('DJEBE', 'Edjene Kossiba', '93 72 33 19', 'Adidogomé', 'Caissière', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('DJETABA', 'Mibawouda', '70 87 28 19', 'Totsi', 'Etudiante', 'Adulte', 50000, 0, 4000, false, NOW(), NOW()),
('DJODJI', 'Koffigné Godwin', '96 32 04 47', '', 'Etudiant', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('DJOKPE', 'Esther', '91 52 83 39', '', 'Styliste', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('DJOMEKOU', '', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('DJONDO', 'Afiwavi Anastasie', '90 27 78 00', '', 'Revendeuse', 'Adulte', 50000, 0, 5000, false, NOW(), NOW()),
('DOGBATSE', 'Géné', '', '', '', 'Adulte', 250000, 0, 0, false, NOW(), NOW()),
('DOGBATSE', 'maman', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('DOGBATSE', 'Kokou', '', '', '', 'Adulte', 250000, 0, 0, false, NOW(), NOW()),
('DOGBATSE', 'Akpédze', '70 10 44 70', '', 'Secrétaire commerciale', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('DOGBATSE (Servte)', 'Kaka', '', '', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('DOGBLA', 'Abigail', '93 02 33 54', 'Agbalepedo', 'Etudiante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('DOKOU', 'Afi', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('DOMEVO', 'Ami Esther', '98 96 46 81', 'Djidjolé', 'Blanchiseur', 'Adulte', 60000, 0, 5000, false, NOW(), NOW()),
('DOUMASSI', 'Géorges', '92 10 81 83', '', 'Etudiant', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('DOUMEHA', 'Anyizan Acquilas', '98 83 72 09', 'Sagbado', 'Caissier', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('DOVI', 'Djatougbé Makpehoda', '90 19 65 84', 'Adidogomé', '', 'Adulte', 100000, 0, 0, false, NOW(), NOW()),
('DOVI', 'Efoé Agbémébia', '90 64 64 66', 'Sagbado', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('DOVI', 'Florence', '71 99 79 71', '', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('DZIKOUNOU', 'Akpenè', '90 46 37 80', 'Djidjolé', 'Pharmacienne', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('DZOMEKU', 'Michal', '', '', '', 'Adulte', 30000, 0, 0, false, NOW(), NOW()),
('EDA', 'Koffi Daniel', '96 15 27 03', 'Lankouvi', 'Entrepreneur', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('EDAH', 'Déborah', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('EDAH', 'Léon', '', '', '', 'Adulte', 100000, 0, 0, false, NOW(), NOW()),
('EDOH', 'Dagan Anna', '97 00 29 04', 'Lomégan', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('EDOU', 'Suzanne', '92 06 97 23', '', 'Commerçante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('EKOUTSE', 'Ablagan', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('EKOUTSE', 'Gloria', '91 41 65 70', 'Totsi', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('EKOUTSE', 'Akou Eyram', '91 41 65 55', 'Avedji', 'Gestionnaire comptable', 'Adulte', 100000, 0, 0, false, NOW(), NOW()),
('EKOUTSE', 'Ablagan Ina', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('EKOUTSE', '', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('ESSATSE', 'Eya', '90 92 53 84', '', 'Ménagère', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('ESSE', 'Agnes', '98 42 80 50', 'Gblékome', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ESSE', 'Labissi', '99 26 79 89', 'Totsi', 'Revendeuse', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('ESSMITHALIME', 'Jane', '', '', '', 'Adulte', 10000, 0, 2000, false, NOW(), NOW()),
('ESSOTINA', 'Grâce', '93 60 93 79', 'Djidjolé', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('EYOU', 'Yogan Eliké', '97 76 44 90', 'Agoe', 'Auditeur comptable', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('FADEGNON', 'James E.', '92 98 77 10', 'Totsi', 'Employé', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('FANDEWOU', 'Adjo Chantal', '93 87 96 00', 'Totsi', 'Stagiaire', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('FANGNON', 'Jean-Eudes Paul', '', 'Djidjolé', 'Commerçant', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('FATIME-ZARA', 'Tcheguena', '90 80 31 09', 'Tokoin séminaire', 'Etudiante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('FAYA', 'Rita', '91 11 08 53', '', 'Couturière', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('FEKI', 'Samuel', '92 81 49 85', 'Djidjolé', 'Electricien/Plombier', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('FEKI', 'Essossima', '96 10 07 48', 'Djidjolé', 'Etudiant', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('FONDOU', 'Koudjoukalo Juliette', '79 14 62 78', '', 'Commerçante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('FONGBEDJI', 'Kokou Peter', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('FONGBEDJI', 'Kokou Roi', '91 89 32 14', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('FONGBEDJI', 'K. Peter', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('GADO', 'La famille', '', '', '', 'Adulte', 1000000, 0, 0, false, NOW(), NOW()),
('GAKPETO', 'Komi Hénoc', '', '', 'Etudiant', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('GAKPETO', 'Afi Ruth', '', '', 'Etudiante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('GAKPETO (Anc)', 'Seth', '', '', '', 'Adulte', 1000000, 0, 0, false, NOW(), NOW()),
('GANYRAKU', 'Julien', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('GBADAMASSI', 'Issa Kokou Désiré', '90 24 92 81', 'Legbassito', 'Enseignant', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('GBATA', 'Eya Akpénè', '98 99 36 88', '', 'Couturière', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('GBEBE', 'Akossiwa Mawuli', '97 28 91 29', 'Wessome', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('GBEFAN', 'Akoele', '93 88 71 29', '', 'Couturière', 'Adulte', 100000, 0, 0, false, NOW(), NOW()),
('GBENOU (Servte)', 'Delali Yawa', '90 74 68 45', 'Totsi', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('GBENOUGA', 'Solange', '90 22 41 81', 'Cacaveli', 'Commerçante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('GBODJO', 'Akuwa', '93 65 31 75', '', 'Revendeuse', 'Adulte', 10000, 0, 2000, false, NOW(), NOW()),
('GBOKLI', 'Bénédicte Estelle', '98 01 54 96', '', 'Etudiante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('GBOKLI', 'Stéphanie Gloria', '93 04 33 62', '', 'Juriste', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('GBOKLI', 'Jeannette', '91 94 37 39', 'Forever', '', 'Adulte', 50000, 0, 5000, false, NOW(), NOW()),
('GOGOBLI', 'Kossi Appolinaire', '90 10 79 49', '', 'Soudeur/Ferailleur', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('GUEDOH (Servte)', 'Abla Akpene', '91 21 96 64', 'Amadahomé', 'Comptable', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('GUENOU', 'Adjogan Bernadette', '92 34 99 23', 'Agbalepedo', 'Etudiante', 'Adulte', 30000, 0, 0, false, NOW(), NOW()),
('HOAFE', 'Akpedje Reine', '71 52 38 12', 'Avenou', 'Apprenti', 'Adulte', 5000, 0, 0, false, NOW(), NOW()),
('HODO', 'Adjovi Essé', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('HODOME', 'Ama Christine', '91 53 45 45', 'Totsi', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('HOEDE', 'Kossi Joseph', '92 52 58 36', '', 'Etudiant', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('HOLONOU', 'Yawo Joel', '90 54 02 00', 'Batomé', 'Styliste', 'Adulte', 100000, 0, 5000, false, NOW(), NOW()),
('HOLONOU', 'Bella Esther', '99 03 92 72', 'Djidjolé', 'Secrétaire comptable', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('HONOU', 'Akou Nina Ruth', '99 71 25 74', 'Gblékome', 'Comptable', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('HOSSE', 'Esther Apefa', '96 91 70 83', 'Totsi', 'Etudiante', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('HOUMEY', 'Albertine', '97 38 81 69', 'Agbalepedo', 'Couturière', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('HOUNAKEY', 'Komla Seyram', '93 56 05 97', 'Agbalepedo', 'Enseignant', 'Adulte', 50000, 0, 50000, false, NOW(), NOW()),
('HOUNOU', 'Odile', '96 21 26 22', 'Totsi', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('HOUSSIMEY', 'Yves Abdoulaye', '93 84 64 97', 'Avedji', 'Chauffeur', 'Adulte', 25000, 0, 0, false, NOW(), NOW()),
('IDOH', 'Gentille', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('IDOH', 'Afowa Charité', '96 40 45 55', 'Avedji', 'Assistante secrétaire', 'Adulte', 50000, 0, 10000, false, NOW(), NOW()),
('IDRISSOU', 'Faita Ida', '90 39 47 47', 'Legbassito', 'Couturière', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KADA', 'Komlan Hervé', '91 51 63 11', '', 'Etudiant', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KADI', 'Komi D. Blank', '90 97 25 95', '', 'Chaudronier', 'Adulte', 30000, 0, 0, false, NOW(), NOW()),
('KAHOUN', 'Afi', '', '', '', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('KAKPO', 'Adjovi', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('KAMFITIME', 'Mariama', '90 83 32 81', 'Batomé', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KANTAGBA', 'Sibédi Jean', '91 86 09 38', 'Totsi', 'Commerçant', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KAZOTTI', 'Bénédicte', '90 71 07 28', 'Attikoumé', 'Etudiante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KETCHEYA', 'Essodinam', '90 73 63 61', '', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KETO', 'Yawo Raphael', '93 09 05 90', 'Gblékome', 'Agent de sécurité', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KLUMSUN-EKLU', 'Tanti', '90 26 34 32', '', 'Commerçante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KODOE', 'Bathelemy', '', '', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KOKOU', 'Yakolé David', '91 08 92 30', '', 'Gestionnaire comptable', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('KOLANI', 'Bettié Nicole', '92 03 02 56', '', 'Enseignante', 'Adulte', 100000, 0, 0, false, NOW(), NOW()),
('KOLEDJI', 'Akouvi Estelle', '98 78 20 09', 'Amadahomé', 'Kinésithérapeute', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('KONON', 'Akouvi E. Lucie', '97 01 18 13', 'Agbalepedo', 'Etudiante', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('KOTO', 'Komi Hermanon', '97 33 42 77', 'Totsi', 'Serigraphe', 'Adulte', 5000, 0, 0, false, NOW(), NOW()),
('KOUDJODJI', 'Holali Adzo', '96 85 15 56', '', 'Apprentis couturière', 'Adulte', 20000, 0, 5000, false, NOW(), NOW()),
('KOUKOU', 'Dagan Josephine', '98 66 81 75', '', 'Etudiante', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('KOULOUMA', 'Méhéza', '99 88 13 87', 'Agoe téléssou', 'Gendarme', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('KOULOUMA', 'Yawa Valerie', '92 91 49 32', 'Agoe téléssou', 'Commerçante', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('KOUMAKPO', 'K. Grâce', '', '', '', 'Adulte', 100000, 0, 0, false, NOW(), NOW()),
('KOUNAKEY', 'Jeanne', '', '', '', 'Adulte', 10000, 0, 500, false, NOW(), NOW()),
('KOUSSOUGBO', 'Komlan Roméo', '91 82 01 73', 'Adidogomé', 'Opérateur de production', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KOUTONIN', 'Kodjovi Mawounyo', '90 62 14 78', 'Avedji', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KOWOU', 'Christine', '93 55 66 73', 'Totsi', 'Agent commercial', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KPADJA', 'Komlan Sébastien', '90 66 09 97', 'Agoe Minamadou', 'Etudiant', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KPAGNATE', 'Kodjo Samuel', '70 16 25 73', 'Djidjolé', 'Etudiant', 'Adulte', 25000, 0, 0, false, NOW(), NOW()),
('KPATA', 'Komi Sidoine', '90 75 43 31', '', 'Comptable', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KPATAROU', 'François A.A.N.', '93 89 68 78', 'Djidjolé', 'Ingénieur génie civil', 'Adulte', 250000, 0, 0, false, NOW(), NOW()),
('KPATAROU', 'Pô-pia Passimssowé', '91 00 62 60', 'Djidjolé', 'Juriste', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KPEGLO', 'Josephine', '', '', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KPEME', 'Kossiwa Maurise', '70 17 17 58', 'Totsi', 'Commerçante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KPODJA', '', '', '', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KPODJRO', 'Kodjo Saka', '79 43 26 77', 'Gbodossime', 'Tepissier', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KPODJRO', 'Adjoa Victorine', '98 61 10 88', 'Gbodossime', 'Receptionniste', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('KPOGAN', 'Akpenè', '90 71 93 67', 'Totsi', 'Revendeuse', 'Adulte', 100000, 0, 0, false, NOW(), NOW()),
('KPOTIMA', 'Brigitte', '91 09 89 99', 'Totsi', 'Commerçante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('LABIKOBIK', 'Adéline', '', '', '', 'Adulte', 10000, 0, 2000, false, NOW(), NOW()),
('LAMBONI', 'Immaculée', '', '', '', 'Adulte', 25000, 0, 0, false, NOW(), NOW()),
('LAOUWAI', 'Kouchouka', '90 14 51 48', '', 'Ménagère', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('LAOUWAÏ', 'Kouchouka', '', '', '', 'Adulte', 250000, 0, 0, false, NOW(), NOW()),
('LARE', 'Bénalélé', '93 01 90 54', '', 'Etudiante', 'Adulte', 15000, 0, 0, false, NOW(), NOW()),
('LARE', 'Bénamdja', '92 73 11 42', '', 'Commerçant', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('LEGUEDE', 'Afi Vitoire', '72 08 63 27', '', 'Etudiante', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('LEGUEDE', 'Ayavi Kékléli', '93 82 73 67', '', 'Etiudiante', 'Adulte', 5000, 0, 0, false, NOW(), NOW()),
('LOKOSSOU', 'Suzanne', '', '', '', 'Adulte', 15000, 0, 0, false, NOW(), NOW()),
('MABE', 'G. Rosaline', '70 38 70 26', 'Glekome', 'Etudiante', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('MABE', 'Joseph', '91 24 34 08', '', 'Tailleur', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('MABE (Anc)', 'Alain', '', '', '', 'Adulte', 250000, 0, 0, false, NOW(), NOW()),
('MAHOEDEOU', 'Henoc Gérard', '98 92 88 73', '', 'Etudiant', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('MAKPOR', 'Kafui', '91 12 66 93', 'Totsi', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('MALIBIDA', 'Bertine', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('MASSEDE', 'JEREMY', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('MASSEDE', 'Kodjo Emmanuel', '90 11 82 13', '', 'Etudiant', 'Adulte', 5000, 0, 0, false, NOW(), NOW()),
('MAWOU', 'Adjovi Guillomé', '91 54 89 26', 'Novissi', 'Gestionnaire de base', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('MEHOUE', 'Josué', '71 32 90 11', 'Totsi', 'Etudiante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('MEHOUE', 'Gédéon', '70 45 11 69', 'Totsi', 'Etudiante', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('MEHOUE', 'Esther', '99 09 72 76', 'Totsi', 'Coiffeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('MENSAH', 'Koffi Léon', '70 46 46 14', 'Lomégan', 'Etudiant', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('MENSAH-DOMKPIN', 'Tele', '98 75 07 54', '', 'Coiffeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('METO', 'Melanie', '93 03 97 01', 'Djidjolé', 'Commerçante', 'Adulte', 5000, 0, 5000, false, NOW(), NOW()),
('METSOMI', 'Béatrice', '', '', '', 'Adulte', 30000, 0, 0, false, NOW(), NOW()),
('METSOMI', 'Koffi Nowa', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('MEWOUNOU', 'Solange', '92 06 23 89', 'Agbalepedo', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('MILEGNE', 'Adjo Essé', '91 38 34 61', '', 'Coiffeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('MINGA', 'Olivia', '93 51 00 57', 'Totsi', 'Secrétaire', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('NAMBIA', 'Esther', '', 'Agoe Sogbossito', 'Elève', 'Adulte', 10000, 0, 500, false, NOW(), NOW()),
('NINKA', 'Komlan', '', 'Totsi', '', 'Adulte', 500000, 0, 0, false, NOW(), NOW()),
('NOUKALA', 'Koami', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('NOUKALA', 'Déborah', '', '', '', 'Adulte', 10000, 0, 5000, false, NOW(), NOW()),
('NOUMONVI', 'Diane', '91 83 44 00', '', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('NOUMOVI-ZOLA', 'Charlotte Abra', '70 61 95 36', '', 'Etudiante', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('OBOUSSOUM', 'Koffi', '91 64 77 71', 'Adidoadin', 'Chauffeur', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ODJI', 'Grâce', '79 76 67 80', 'Lomégan', 'Etidiante', 'Adulte', 50000, 0, 5000, false, NOW(), NOW()),
('ODJI', 'K. A. Jacques', '92 68 35 81', 'Batomé', 'Enseignant', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('ODJI', 'Yaovi Jean', '', '', '', 'Adulte', 50000, 0, 1000, false, NOW(), NOW()),
('OGOUMEDJI', 'Simon', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('OHOUSSROU', 'Komi', '70 30 70 32', 'Sanguéra', 'Technicien portable', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('OKOUMA', 'Divine', '', '', '', 'Adulte', 15000, 0, 0, false, NOW(), NOW()),
('OUGANI-TCHAPO', 'Jeanne', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('OUGANI-TCHAPO', 'Gnamba Rosaline', '91 01 36 24', '', 'Productrice', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('OUPEL', 'Géneviève', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('PAGNI', 'N''maa Edith', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('PAKA (Servt)', 'Mathias', '', '', '', 'Adulte', 250000, 0, 0, false, NOW(), NOW()),
('PAKOUYOSSO', 'E. Marie-Madelène', '97 81 86 88', 'Djidjolé', 'Etudiante', 'Adulte', 30000, 0, 0, false, NOW(), NOW()),
('PAROU', 'Sylvain', '93 88 43 12', 'Djidjolé', 'Pharmacien', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('PEYELEKE', 'Dialo', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('PIGNANDI', 'Judith Essoyomewé', '90 89 41 46', 'Gblékome', 'Revendeuse', 'Adulte', 30000, 0, 0, false, NOW(), NOW()),
('PILESSABALA', 'Alooudè Brigitte', '92 96 56 26', 'Sogbossito', 'Gestionnaire comptable', 'Adulte', 50000, 0, 50000, false, NOW(), NOW()),
('PILESSABALA', 'M. Lucien', '90 35 38 32', 'Sogbossito', '', 'Adulte', 100000, 0, 100000, false, NOW(), NOW()),
('POTOKPISSI', 'Mamaline Esso', '93 57 43 45', 'Djidjolé', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('POUKPEZI', 'Essonyim Obed', '93 15 00 84', 'Agoe Minamadou', 'Ingénieur agroalimentaire', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('POUKPEZI', 'E. Obed', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('POULI', 'LIDAO', '', '', '', 'Adulte', 300000, 0, 0, false, NOW(), NOW()),
('POULI', 'WALA', '', '', '', 'Adulte', 10000, 0, 5000, false, NOW(), NOW()),
('POULI', 'B. Jacqueline', '90 83 15 92', '', 'Administrateur civil', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ROBIN', 'Koffi Mawulipklimi', '99 53 54 39', 'Amadahomé', 'Artiste en art', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('SALIFOU', 'Afondé', '', '', '', 'Adulte', 100000, 0, 0, false, NOW(), NOW()),
('SAND', 'Régina', '93 23 50 46', 'Totsi', 'Accoucheuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('SANNI', 'Afi Aristida', '92 19 35 46', 'Adidogomé', 'Etudiante', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('SANNI', 'Nelson Gracio', '98 97 61 40', 'Adidogomé', 'Elève', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('SANNI (Anc)', 'Saliou Jules Adissa', '90 30 93 76', 'Adidogomé', 'Assistant médical', 'Adulte', 500000, 0, 0, false, NOW(), NOW()),
('SEDJRO', 'Joél', '', '', '', 'Adulte', 100000, 0, 0, false, NOW(), NOW()),
('SEMOU', 'Akesso', '99 03 36 63', '', 'Gestionnaire', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('SEMOUDZE', 'Abra Sitsope', '97 95 65 27', 'Adidogomé', 'Etudiante', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('SEWA', 'Victoire', '', '', '', 'Adulte', 10000, 0, 0, false, NOW(), NOW()),
('SEWOVON', 'Kodjo E; Sélom', '', '', '', 'Adulte', 15000, 0, 2000, false, NOW(), NOW()),
('SODEHOUNDJA', 'Ablavi Emefa', '93 72 41 43', '', 'Couturière', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('SODJIHOUN', 'Marie Florence', '90 59 77 93', '', 'Apprentis coiffeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('SOKAME', 'Akouvi Rogate', '92 65 19 65', '', 'Coiffeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('SOKOME', 'Lozès', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('SOLEDJI', 'Amélé Esse', '91 26 86 34', 'Djidjolé', 'Couturière', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('SOSSA (Anc)', '', '', '', '', 'Adulte', 8000000, 0, 0, false, NOW(), NOW()),
('SOSSOU', 'Akouto Therese', '92 15 04 81', 'Agoe Minamadou', 'Styliste', 'Adulte', 5000, 0, 0, false, NOW(), NOW()),
('SOSSOU', 'Abla', '92 42 50 66', '', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('SOUMONOU', 'Augustine', '90 51 12 68', 'Agbalepedo', 'Employé', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('SYLLI', 'Adjo Egnonam Clarisse', '92 05 88 48', 'Totsi', 'Etudiante', 'Adulte', 30000, 0, 0, false, NOW(), NOW()),
('TAMAME', 'B. Matthieu', '', '', '', 'Adulte', 250000, 0, 0, false, NOW(), NOW()),
('TANAN', 'Moïse', '', '', '', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('TCHAMDJA (Servt)', 'Fabrice', '', '', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('TCHAOAGO', 'Essowanam Nicole', '98 45 79 19', 'Totsi', 'Ménagère', 'Adulte', 2000, 0, 0, false, NOW(), NOW()),
('TCHINKE', 'Komla Samuel', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('TCHONKPONHOE', 'Kokou Rodrigue', '93 22 54 19', 'Djidjolé', 'Magasinier', 'Adulte', 20000, 0, 0, false, NOW(), NOW()),
('TCHOWOU', 'Essolakina Hervé', '91 09 70 48', '', 'Juriste en formation', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('TENGUE', 'Akou Justine', '97 99 87 06', 'Gblékome', 'Couturière', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('TETEBANAN', 'E. Kossi', '', '', '', 'Adulte', 30000, 0, 0, false, NOW(), NOW()),
('TOARE (Servt)', 'Yéndoubé', '', '', '', 'Adulte', 500000, 0, 0, false, NOW(), NOW()),
('TODZE', 'Kwadzo', '', '', '', 'Adulte', 5000, 0, 500, false, NOW(), NOW()),
('TODZE', 'Akou Mokpokpo', '93 05 36 80', 'Wessome', 'Elève', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('TOGAN', 'Komlanvi Crépin', '90 16 48 98', 'Totsi', 'Technicien supérieur en télécomunication', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('TOGAN (Servt)', 'Crépin', '', '', '', 'Adulte', 100000, 0, 0, false, NOW(), NOW()),
('TOGBE', 'Assoupi Jeannette', '90 75 87 90', 'Agbalepedo', 'Ménagère', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('TOHOEDE', 'Koffi', '93 06 41 06', 'Djidjolé', 'Agent de sécurité', 'Adulte', 15000, 0, 0, false, NOW(), NOW()),
('TOHOEDE', 'Kossiba', '90 78 40 94', 'Gblékome', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('TOHOEDE', 'Komi Espoir', '93 36 85 78', '', 'Coiffeur', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('TOHOINDE', 'Adjowa', '91 02 02 69', '', 'Revendeuse', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('TOULASSI', 'Djigbodi', '99 56 60 82', 'Totsi', 'Commerçante', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('TOULASSI', 'Essé Nadège', '71 28 20 37', 'Totsi', 'Elève', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('TOUWALA', 'Essosimna', '92 25 77 02', 'Agoe kitigan', 'Notoyage à BB', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('TOZO', 'Amavi Fatouma', '', '', '', 'Adulte', 250000, 0, 0, false, NOW(), NOW()),
('TSAKPASSOU', 'Kokou Judith', '90 39 70 73', '', 'Etudiant', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('TSOWU', 'Julienne', '', '', '', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('TSRIGBIDI', 'A. Célestine', '', '', '', 'Adulte', 30000, 0, 2000, false, NOW(), NOW()),
('WAGBA', 'Mina Akou Deladem', '92 50 16 22', 'Batomé', 'Couturière', 'Adulte', 50000, 0, 5000, false, NOW(), NOW()),
('WANTAR', 'Ajidmmaa', '', '', 'Couturière', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('WOMI', 'Ayawa Ana', '99 89 11 05', 'Agbalepedo', 'Revendeuse', 'Adulte', 50000, 0, 0, false, NOW(), NOW()),
('YAKAWOU(Anc)', 'Joel', '', '', '', 'Adulte', 500000, 0, 0, false, NOW(), NOW()),
('YAME', 'Kouatipoa', '90 83 32 81', '', 'Ménagère', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('YEBOU', 'Chantal', '92 89 93 30', 'Djidjolé', 'Couturière', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('YEBOU', 'Jean', '90 76 08 77', 'Djidjolé', 'Commerçant', 'Adulte', 200000, 0, 0, false, NOW(), NOW()),
('YOVO', 'Abla Grace', '70 99 60 51', '', 'Etudiante', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('YOVO (Anc)', '', '', '', '', 'Adulte', 0, 0, 0, false, NOW(), NOW()),
('ZINSOU', 'Zinsi Crépine', '97 06 23 43', 'Soviépé', 'Coiffeuse', 'Adulte', 250000, 0, 0, false, NOW(), NOW()),
('ADIKANOU', 'Reine', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ADJESSON', 'Kodjo', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ADJONOU', 'Uriel Abla', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ADODO', 'Mawugnon Wlys', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ADODO', 'Mawugnon', '', '', '', 'Enfant', 500, 0, 0, false, NOW(), NOW()),
('ADOELLA', 'Adetoutou Néhémiah', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ADOELLA', 'Adeleke Yawo Sethiel', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ADOELLA', 'Adeyemo Mathias', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ADONSI', 'Yao Bruno', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AFORI', 'Francis', '', '', '', 'Enfant', 2000, 0, 0, false, NOW(), NOW()),
('AGBA', 'Monique', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AGBALENYO', 'Abigel', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AGBANDJRO', 'Prospère', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AGBANDJRO', 'Linavi', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AGBANDJRO', 'Victoire', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AGBANDJRO', 'Achille', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AGBANDRO', 'Komivi Prosper', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AGBANVON', 'Komlan A.', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AGBEGNIDO', 'Divine', '', '', 'Elève', 'Enfant', 10000, 0, 0, false, NOW(), NOW()),
('AGBEGNIDO', 'Maharaim', '', '', 'Elève', 'Enfant', 50000, 0, 0, false, NOW(), NOW()),
('AGBEGNIDO', 'Merveille', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AGBEKPIE', 'Ami Domiane', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AGBESSI', 'Emmanuella', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AGBEZOUDJRO', 'Abla', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AGBOLESSOU', 'Yawa Cathérine', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AGLI', 'Parfaite', '', '', 'Elève', 'Enfant', 10000, 0, 0, false, NOW(), NOW()),
('AHIAGBA', 'Béni Oracle', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AHIAGBA', 'Béni Prodige', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AHISSOU', 'Naomi Bernice', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AHOLOU', 'Yawa Annaëlle', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AKOSSOU', 'Séphora', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AKOSSOU', 'Kekeli', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AKOSSOU', 'Séréna', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ALEMA', 'Joseph', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ALENA', 'Gédéon', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ALOHO', 'Rufine', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AMELONKOU', 'Yoan Djidula', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AMELONKOU', 'Venougné Maëlle', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AMEZADO', 'Emmanuella', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AMOSSOU', 'Edoh Théophile', '', '', '', 'Enfant', 5000, 0, 0, false, NOW(), NOW()),
('AMOU', 'Dorcas', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AMOUZOUVI', 'Augustine', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ANIKE', 'Ablavi Manasse', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ANIMAKA', 'Alida', '', '', '', 'Enfant', 2000, 0, 0, false, NOW(), NOW()),
('ASSE', 'Jame', '', '', '', 'Enfant', 5000, 0, 0, false, NOW(), NOW()),
('ASSIAGBO', 'Rhéma', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ASSOGBA', 'Arthur', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ASSOGBA', 'Koffi Arthur', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ATOESSI', 'Bénédicte', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ATOESSI', 'Oliver', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ATOESSI', 'Rachelle', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ATOESSI', 'Atsu', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AYANOU', 'Prince', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AYANOU', 'Emmanuella', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AYANOU', 'Akouvi Grâce', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AYITE', 'Komi Nutifafa Bathelemy', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AZIADOME', 'Yayra', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('AZIADOME', 'Rebecca', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('BALAKIME', 'Célestine', '', '', '', 'Enfant', 5000, 0, 0, false, NOW(), NOW()),
('BARNABO', 'Victoire', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('BARNABO', 'Wonder', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('BARNABO', 'Ariel', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('BAY-YABA', 'Josias', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('BOKOSSA', 'Adjoavi Bernice', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('DAOU', 'Elisée', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('DAOU', 'Emmanuel', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('DEGBE', 'Elisé', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('DEGBE', 'Djiédjome Noeline', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('DELE', 'Koffi Felix', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('DEVI', 'Kossivi Jonas', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('DJAMESHIE', 'Josué', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('DJAMESHIE', 'Othniel', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('DJAMESHIE', 'Japhet', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('DJAMESSI', 'Bethel', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('DOGBATSE', 'Kemuel', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('DOMEVO', 'Abla Bernice', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('DORKENOO', 'Péniel', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('DOUMASSI', 'Gustave', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('EDAH', 'Akosse', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('EDAH', 'Fleur', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('EDAH', 'Céline', '', '', 'Elève', 'Enfant', 10000, 0, 0, false, NOW(), NOW()),
('EKLU', 'Afi Evania', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('EKOUTSE', 'Jemima', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('EKOUTSE', 'Ablagan Marie', '', '', 'Etudiante', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ELAVAHO', 'Gaëlle', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ETAO', 'Mélébé', '', '', '', 'Enfant', 7000, 0, 0, false, NOW(), NOW()),
('FANDEWOU', 'Adjovi Huberline', '', '', 'Elève', 'Enfant', 5000, 0, 0, false, NOW(), NOW()),
('FONGBEDJI', 'Prudence', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('GABIA', 'Afi Sandra', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('GAKPETO', 'Ephraïm Junior', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('GBOKLI', 'Bénédicte', '', '', 'Etudiante', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('GBOKLI', 'Ezechiel Richard', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('GLIKPO', 'Cathérine', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('GNININVI', 'Angelo', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('GNININVI', 'Light', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('HODO', 'Akou Victoire', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('HOLONOU', 'A. Samuel', '', '', '', 'Enfant', 5000, 0, 0, false, NOW(), NOW()),
('IDRISSOU', 'Wisdom', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('JONHSON', 'Sheila Grâce', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KADI', 'Akpene', '', '', '', 'Enfant', 5000, 0, 0, false, NOW(), NOW()),
('KAKPO', 'Adjovi', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KAKPO', 'Chiba Odille', '', '', 'Coiffeuse', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KALABINA', 'Abire', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KALABINA', 'Mazalo Magnoulleley', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KANTAGBA', 'Béni', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KANTAGBA', 'Chantal', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KANTAGBA', 'Emmanuella', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KETSATSA', 'Blandine', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KITEKI', 'Adjo', '', '', 'Couturière', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KLAKE', 'Kokou Ferdinand', '', '', 'Etudiant', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KODOE', 'Yawa Favour', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KODOE', 'Kokou Femos', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KOKOU', 'Mawugnon Merveille', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KOUNAKE', 'Djodjina', '', '', '', 'Enfant', 5000, 0, 0, false, NOW(), NOW()),
('KOUNAKEY', 'Kelinde Clémence', '', '', '', 'Enfant', 5000, 0, 0, false, NOW(), NOW()),
('KOUTCHENE', 'Akpene', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KOUTONIN', 'Komi Ephraïm', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KOUTONIN', 'Afi Emmanuela', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KOUTONIN', 'Afi Gloria', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KPADJA', 'Adjogan', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KPAGAN', 'Gladys', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KPEKPENDI', 'Mirielle', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KPEKPENDI', 'Paul', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KPIZIA', 'Béni', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KPIZIA', 'Exaucé', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('KPODJI', 'Nadège', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('LAMBONI', 'Souko Elise', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('LAMBONI', 'Minoba', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('MABE', 'Triomphe', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('MABE', 'Grâce', '', '', 'Elève', 'Enfant', 10000, 0, 0, false, NOW(), NOW()),
('MACAMANZI', 'Miguel Gnoulélén', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('MACAMANZI', 'Lelenda Miché', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('MACAMANZI', 'K. Angelica', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('MALONGO', 'Christal C. Emmanuelle', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('NAYO', 'Yves', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('N''DAH', 'Merveille', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('N''DAH', 'Eloge', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('N''DAH', 'Kayebo Joseph', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('NOUKALA', 'Amévi Merveille', '', '', '', 'Enfant', 10000, 0, 0, false, NOW(), NOW()),
('OFORI', 'Koffi Francis', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('PAKA', 'Essodeo', '', '', 'Elève', 'Enfant', 10000, 0, 0, false, NOW(), NOW()),
('PAROU', 'Robert', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('PAROU', 'Laure', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('POTCHO', 'Bella', '', '', '', 'Enfant', 1000, 0, 0, false, NOW(), NOW()),
('POTOKPISSI', 'Noeline', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('POTOKPISSI', 'Mamawesso', '', '', '', 'Enfant', 1000, 0, 0, false, NOW(), NOW()),
('POULI', 'Juliette', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('SANNI', 'Nelson', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('SEDOR', 'Prosper', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('SEDOR', 'Maruis', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('SEDOR', 'Wilrich', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('SETODJI', 'Ami Kekeli', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('SIOU', 'Préname', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('SODJIHOUN', 'Patricia', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('SOMENOU', 'Abla', '', '', '', 'Enfant', 500, 0, 500, false, NOW(), NOW()),
('SOMISSOU', 'Komlan Yanis', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('SOMISSOU', 'Elikem Audrey', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('SOSSA', 'Rejoyce', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('SOSSA', 'Eunice', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('SOSSA', 'Caleb', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('SOSSOU', 'Bénédicta', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('SOSSOU', 'Jules', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('SOSSOU', 'Julia Eunice', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('SOWANOU', 'Kokou Edoh', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('SOWANOU', 'Komla Emmanuel', '', '', '', 'Enfant', 5000, 0, 0, false, NOW(), NOW()),
('TAYELI', 'Anita Julienne', '', '', 'Etudiante', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TCHALIM', 'Magnim', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TCHALIM', 'Mèhèza Majoie', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TCHAMDJA', 'Fierte', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TCHAMDJA', 'Prométhée', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TCHATENANGBON', 'Justine', '', '', '', 'Enfant', 5000, 0, 0, false, NOW(), NOW()),
('TEDE', 'Kokouvi Elie Carlos', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TETE', 'Bernice', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TETE', 'Emmanuella', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TOARE', 'Zoé', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TODJE', 'Elise', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TODO-ALIPUI', 'Joane Kokou', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TODZE', 'Eyrame', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TOGAN', 'Komlan Yedidia', '', '', 'Elève', 'Enfant', 10000, 0, 0, false, NOW(), NOW()),
('TOGODO', 'Oracle', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TOHOEDE', 'Yaovi Samuel', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TOHOEDE', 'Seynam', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TOHOEDE', 'Akouvi Lumière', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TOHOEDE', 'Komla Magloire', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TOULASSI', 'Kodzo Daniel', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TOULASSI', 'Akossiwavi', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('TREVE', 'Kodjo', '', '', '', 'Enfant', 5000, 0, 0, false, NOW(), NOW()),
('WASSIKE', 'Marcelin', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('YAKAWOU', 'Shalom', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('YAKAWOU', 'Grâce', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('YAKAWOU', 'Excaucé Mawulikplim', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('YEBOU', 'Daniel', '', '', 'Elève', 'Enfant', 2000, 0, 0, false, NOW(), NOW()),
('YEBOU', 'Gracia Bella', '', '', 'Elève', 'Enfant', 2000, 0, 0, false, NOW(), NOW()),
('ZAHAUE', 'Antoinette', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ZAHAUE', 'Junior', '', '', '', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ZIGAN', 'Wisdom', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW()),
('ZONHOTSE', 'Emilla', '', '', 'Elève', 'Enfant', 0, 0, 0, false, NOW(), NOW());